// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Task struct {
	ID          int32
	Titulo      string
	Descripcion string
	Estado      string
	Prioridad   string
	CreadoEn    time.Time
	Vencimiento sql.NullTime
}
