// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    titulo,
    descripcion,
    estado,
    prioridad,
    vencimiento
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, titulo, descripcion, estado, prioridad, creado_en, vencimiento
`

type CreateTaskParams struct {
	Titulo      string
	Descripcion string
	Estado      string
	Prioridad   string
	Vencimiento sql.NullTime
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Titulo,
		arg.Descripcion,
		arg.Estado,
		arg.Prioridad,
		arg.Vencimiento,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Estado,
		&i.Prioridad,
		&i.CreadoEn,
		&i.Vencimiento,
	)
	return i, err
}

const deleteCompletedTasks = `-- name: DeleteCompletedTasks :execresult
DELETE FROM tasks
WHERE estado = 'Completada'
`

// Limpieza en lote de tareas completadas
func (q *Queries) DeleteCompletedTasks(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCompletedTasks)
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Estado,
		&i.Prioridad,
		&i.CreadoEn,
		&i.Vencimiento,
	)
	return i, err
}

const getTaskMetrics = `-- name: GetTaskMetrics :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE estado = 'Pendiente')::int AS pendientes,
    COUNT(*) FILTER (WHERE estado = 'En Progreso')::int AS en_progreso,
    COUNT(*) FILTER (WHERE estado = 'Completada')::int AS completadas,
    COUNT(*) FILTER (WHERE vencimiento < NOW() AND estado != 'Completada')::int AS vencidas
FROM tasks
`

type GetTaskMetricsRow struct {
	Total       int32
	Pendientes  int32
	EnProgreso  int32
	Completadas int32
	Vencidas    int32
}

// Métricas y estadísticas de tareas
func (q *Queries) GetTaskMetrics(ctx context.Context) (GetTaskMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskMetrics)
	var i GetTaskMetricsRow
	err := row.Scan(
		&i.Total,
		&i.Pendientes,
		&i.EnProgreso,
		&i.Completadas,
		&i.Vencidas,
	)
	return i, err
}

const listCompletedTasksInLastDays = `-- name: ListCompletedTasksInLastDays :many
SELECT
    id,
    titulo,
    descripcion,
    estado,
    prioridad,
    creado_en,
    vencimiento,
    COUNT(*) OVER()::int AS total_completadas
FROM tasks
WHERE estado = 'Completada'
  AND creado_en >= NOW() - ($1::int * INTERVAL '1 day')
ORDER BY creado_en DESC
`

type ListCompletedTasksInLastDaysRow struct {
	ID               int32
	Titulo           string
	Descripcion      string
	Estado           string
	Prioridad        string
	CreadoEn         time.Time
	Vencimiento      sql.NullTime
	TotalCompletadas int32
}

// Tareas completadas en los últimos x dias con conteo total de ventana
func (q *Queries) ListCompletedTasksInLastDays(ctx context.Context, dollar_1 int32) ([]ListCompletedTasksInLastDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedTasksInLastDays, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedTasksInLastDaysRow
	for rows.Next() {
		var i ListCompletedTasksInLastDaysRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
			&i.TotalCompletadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueTasks = `-- name: ListOverdueTasks :many
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
WHERE vencimiento IS NOT NULL
  AND vencimiento < NOW()
  AND estado != 'Completada'
ORDER BY vencimiento ASC
`

// Detección de tareas vencidas
func (q *Queries) ListOverdueTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasksOrderByDueDate = `-- name: ListPendingTasksOrderByDueDate :many
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
WHERE estado = 'Pendiente'
ORDER BY vencimiento ASC NULLS LAST
`

// Ordenar por estado (pendiente) y fecha vencimiento
func (q *Queries) ListPendingTasksOrderByDueDate(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTasksOrderByDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
ORDER BY id ASC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPriority = `-- name: ListTasksByPriority :many
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
WHERE prioridad = $1
ORDER BY id ASC
`

// Filtrado por prioridad (Alta)
func (q *Queries) ListTasksByPriority(ctx context.Context, prioridad string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByPriority, prioridad)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDueInNextDays = `-- name: ListTasksDueInNextDays :many
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
WHERE vencimiento IS NOT NULL
  AND vencimiento BETWEEN NOW() AND NOW() + ($1::int * INTERVAL '1 day')
ORDER BY vencimiento ASC
`

// Tareas que vencen en los siguientes x dias
func (q *Queries) ListTasksDueInNextDays(ctx context.Context, dollar_1 int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksDueInNextDays, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompleted = `-- name: MarkTaskCompleted :one
UPDATE tasks
SET estado = 'Completada'
WHERE id = $1
RETURNING id, titulo, descripcion, estado, prioridad, creado_en, vencimiento
`

// Acción rápida: Marcar tarea como completada
func (q *Queries) MarkTaskCompleted(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, markTaskCompleted, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Estado,
		&i.Prioridad,
		&i.CreadoEn,
		&i.Vencimiento,
	)
	return i, err
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, titulo, descripcion, estado, prioridad, creado_en, vencimiento FROM tasks
WHERE titulo ILIKE '%' || $1::text || '%'
   OR descripcion ILIKE '%' || $1::text || '%'
ORDER BY id ASC
`

// Búsqueda global de palabra clave en título y descripción
func (q *Queries) SearchTasks(ctx context.Context, dollar_1 string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Estado,
			&i.Prioridad,
			&i.CreadoEn,
			&i.Vencimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    titulo = $2,
    descripcion = $3,
    estado = $4,
    prioridad = $5,
    vencimiento = $6
WHERE id = $1
RETURNING id, titulo, descripcion, estado, prioridad, creado_en, vencimiento
`

type UpdateTaskParams struct {
	ID          int32
	Titulo      string
	Descripcion string
	Estado      string
	Prioridad   string
	Vencimiento sql.NullTime
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Titulo,
		arg.Descripcion,
		arg.Estado,
		arg.Prioridad,
		arg.Vencimiento,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Estado,
		&i.Prioridad,
		&i.CreadoEn,
		&i.Vencimiento,
	)
	return i, err
}
